#!/usr/bin/env sh
export FONT="SF Pro"
export NERD_FONT="SFMono Nerd Font"

spacebar -m config position             top
spacebar -m config height               30
spacebar -m config title                off
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "$FONT:Medium:12.0"
spacebar -m config icon_font            "$NERD_FONT:Regular:14.0"
spacebar -m config background_color     0x25ffffff
spacebar -m config foreground_color     0xffB8A598
spacebar -m config space_icon_color     0xffBCD4D4
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config power_icon_strip     􀙬 􀋦
spacebar -m config space_icon_strip     α β γ δ ε ζ η θ ι
spacebar -m config space_icon           
spacebar -m config clock_icon           􀉉
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%m/%d/%y %R"
spacebar -m config right_shell          off
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "whoami"

echo "spacebar configuration loaded.."

